[package]
name = "racf"
version = "1.0.2"
edition = "2021"
authors = [ "explosion-mental" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.14.0"
# starship has forked the battery crate and updated it's dependencies (old nix crate had a vulnerability)
battery = { version = "0.7.*", package = "starship-battery" }
getsys = { git = "https://codeberg.org/explosion-mental/getsys", version = "1.0.0" }
clap = { version = "4.0.29", features = ["derive"] }
toml = "0.5.10"
serde = { version = "1.0.150", features = ["derive"] }
thiserror = "1.0.38"
sysinfo = { version = "0.27.7", default-features = false }


[[bin]]
name = "racf"
path = "racf.rs"
