[package]
name = "racf"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
num_cpus = "1.0.0"
battery = "0.7.8"
getsys = { git = "https://github.com/explosion-mental/getsys" }
clap = { version = "4.0.29", features = ["derive"] }
toml = "0.5.10"
serde = { version = "1.0.150", features = ["derive"] }


[[bin]]
name = "racf"
path = "racf.rs"
