# Two profiles which are enabled depending whether the system is using battery or is charging.
# pd: capitalization doesn't matter.
[battery]

# Always: turbo boost will always be on.
# Never:  turbo boost will never be on.
# Auto:   depending on the cpu usage, system load and temperature, turbo boost will be on/off.
turbo = "auto"

# Percentage of cpu usage where turbo boost is enabled (float) [0.% ... 100.%]
mincpu = 5.0

# Degrees celsius where turbo boost is enabled
# (mind that around 30 - 40 is usually normal usage)
mintemp = 50

# When running in the background, this will be the interval to wake up from
# sleeping and tweak the system (seconds)
interval = 30

# Usual avaliable governors:
# 	performance - powersave - userspace - ondemand - conservative - schedutil
# use -l/--list to check for avaliable values in your system
#
# NOTE FOR INTEL USERS: (modern) intel CPUs have a pstate, which is preferable
# over the cpufreq. As a suggestion, these 'intel specific' governors are:
# 	balance_performance - balance_power
# Check if the path /sys/devices/system/cpu/intel_pstate/hwp_dynamic_boost exist
governor = "powersave"

# OPTIONAL: You can set a frequency, but setting this requires the governor to be 'userspace'.
# (use `-l` for possible values)
#frequency = 2000000

[ac]

turbo = "auto"
mincpu = 30.0
mintemp = 70
interval = 60
governor = "performance"
